[project]
name = "survival-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.17.0",
    "numpy>=2.3.4",
    "plotly>=6.3.1",
    "pandas>=2.3.3"
]
